image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:

  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc

init:
  - git config --global core.autocrlf input

skip_non_tags: true

cache:
  - C:\Users\appveyor\.cargo\registry
  - src-tauri\target\release\build

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - cargo install tauri-cli

  # Install Node.js version 20 using nvm
  - ps: Install-Product node 20
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-NVM.ps1'))
  - nvm install 20
  - nvm use 20

  # Verify Node.js installation
  - node -v
  - npm -v

  # Install project dependencies
  - npm install


build_script:
  - cargo tauri build

test: off

artifacts:
  - path: src-tauri\target\release\bundle\nsis\crmbar-tauri*setup.exe
    name: Setup

  - path: src-tauri\target\release\bundle\nsis\crmbar-tauri*setup.nsis*
    name: Setup-zip

  - path: src-tauri\target\release\bundle\msi\crmbar-tauri*.msi
    name: Setup-msi

  - path: src-tauri\target\release\bundle\msi\crmbar-tauri*.msi*
    name: Setup-msi-zip

deploy:
- provider: GitHub
  auth_token:
    secure: ${{ secrets.GITHUB_TOKEN }}
  artifact: Setup
  draft: false
  file: src-tauri\target\release\bundle\nsis\crmbar-tauri*setup.exe
  on:
    appveyor_repo_tag: true
  release: crmbar-tauri-v$(appveyor_build_version)
  description: 'Automated Build Release'

- provider: GitHub
  auth_token:
    secure: ${{ secrets.GITHUB_TOKEN }}
  artifact: Setup-zip
  draft: false
  file: src-tauri\target\release\bundle\nsis\crmbar-tauri*setup.nsis*
  on:
    appveyor_repo_tag: true
  release: crmbar-tauri-v$(appveyor_build_version)
  description: 'Automated Build Release'

- provider: GitHub
  auth_token:
    secure: ${{ secrets.GITHUB_TOKEN }}
  artifact: Setup-msi
  draft: false
  file: src-tauri\target\release\bundle\msi\crmbar-tauri*.msi
  on:
    appveyor_repo_tag: true
  release: crmbar-tauri-v$(appveyor_build_version)
  description: 'Automated Build Release'

- provider: GitHub
  auth_token:
    secure: ${{ secrets.GITHUB_TOKEN }}
  artifact: Setup-msi-zip
  draft: false
  file: src-tauri\target\release\bundle\msi\crmbar-tauri*.msi*
  on:
    appveyor_repo_tag: true
  release: crmbar-tauri-v$(appveyor_build_version)
  description: 'Automated Build Release'
