version: 1.0.{build}

environment:
  matrix:
    - nodejs_version: "12"
    - nodejs_version: "14"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g tauri

build_script:
  - npm run build

test_script:
  - npm test
